language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$home/.m2/repository'
    - '$home/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r AWS-WebService *
  - mkdir -p deploy
  - mv AWS-WebService.zip deploy/AWS-WebService.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build1
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: milkbottle0305/AWS-WebService
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build1
    key: AWS-WebService.zip
    bundle_type: zip
    application: springboot2-webservice
    deployment_group: springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: milkbottle0305/AWS-WebService
      branch: master

# CI 끝나면 메일로 알람
notifications:
  email:
    recipients:
      - err404@khu.ac.kr